name: Get Changelog from LMS
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Logitech/slimserver
          sparse-checkout: .
          run: |
            cp Changelog8.html ${{ github.workspace }}

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "Release ${{ github.event.inputs.version }}"
          git push
