name: Get Changelog from LMS
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files
        run: |
          curl https://raw.githubusercontent.com/Logitech/slimserver/HEAD/Changelog8.html > changelog-lms8.html

      - name: Convert HTML to Markdown
        id: html2markdown
        if: always()
        uses: rknj/html2markdown@v0.1.0
        with:
          html-file: "changelog-lms8.html"

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add changelog-lms8.md
          git commit -a -m "Update changelog from slimserver repo"
          git push
